[project]
name = "attention-is-all-you-need"
version = "0.1.0"
description = "A minimal implementation of encoder transformer block described in Vaswani et al. https://arxiv.org/pdf/1706.03762"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.9.0",
]
